# -*- coding: utf-8 -*-
from tests import HangulizeTestCase
from hangulize.langs.bul import Bulgarian


class BulgarianTestCase(HangulizeTestCase):

    lang = Bulgarian()

    def test_examples_of_iceager(self):
        assert u'야로슬라프' == self.hangulize(u'Ярослав')
        assert u'미하일' == self.hangulize(u'Михаил')
        assert u'가브릴' == self.hangulize(u'Гаврил')
        assert u'드라간' == self.hangulize(u'Драган')
        assert u'시메온' == self.hangulize(u'Симеон')
        assert u'크룸' == self.hangulize(u'Крум')
        assert u'요한' == self.hangulize(u'Йохан')
        assert u'알렉산더르' == self.hangulize(u'Александър')
        assert u'라도미르' == self.hangulize(u'Радомир')
        assert u'안드레이' == self.hangulize(u'Андрей')
        assert u'콘스탄틴' == self.hangulize(u'Константин')
        assert u'카탸' == self.hangulize(u'Катя')
        assert u'흐리스토' == self.hangulize(u'Христо')
        assert u'빅토리야' == self.hangulize(u'Виктория')
        assert u'랄리차' == self.hangulize(u'Ралица')
        assert u'디미터르' == self.hangulize(u'Димитър')
        assert u'그리고르' == self.hangulize(u'Григор')
        assert u'페터르' == self.hangulize(u'Петър')
        assert u'에밀' == self.hangulize(u'Емил')
        assert u'퍼를리체프' == self.hangulize(u'Пърличев')
        assert u'흐리스토프' == self.hangulize(u'Христов')
        assert u'디미트로프' == self.hangulize(u'Димитров')
        assert u'파블로프' == self.hangulize(u'Павлов')
        assert u'지프코프' == self.hangulize(u'Живков')
        assert u'레치코프' == self.hangulize(u'Лечков')
        assert u'테오도시' == self.hangulize(u'Теодосий')
        assert u'요르다노프' == self.hangulize(u'Йорданов')
        assert u'류드밀라' == self.hangulize(u'Людмила')
        assert u'에카테리나' == self.hangulize(u'Екатерина')
        assert u'메한지스키' == self.hangulize(u'Механджийски')
        assert u'보야지에프' == self.hangulize(u'Бояджиев')
        assert u'게오르기' == self.hangulize(u'Георги')
        assert u'일리야' == self.hangulize(u'Илия')
        assert u'스토이치코프' == self.hangulize(u'Стоичков')
        assert u'인조바' == self.hangulize(u'Инджова')
        assert u'에프스트라티에프' == self.hangulize(u'Евстратиев')
        assert u'듀스타바노프' == self.hangulize(u'Дюстабанов')
        assert u'나자코프' == self.hangulize(u'Наджаков')
        assert u'크러스테바' == self.hangulize(u'Кръстева')
        assert u'그로즈데바' == self.hangulize(u'Гроздева')
        assert u'파라스케바' == self.hangulize(u'Параскева')
        assert u'레체바' == self.hangulize(u'Лечева')
        assert u'두르무슐리스카' == self.hangulize(u'Дурмушлийска')
        assert u'댜코프스카' == self.hangulize(u'Дяковска')
        assert u'머르크비치카' == self.hangulize(u'Мърквичка')
        assert u'코스타디노프' == self.hangulize(u'Костадинов')
        assert u'베르바토프' == self.hangulize(u'Бербатов')
        assert u'플로브디프' == self.hangulize(u'Пловдив')
        assert u'부르가스' == self.hangulize(u'Бургас')
        assert u'파나규리슈테' == self.hangulize(u'Панагюрище')
        assert u'아세노브그라드' == self.hangulize(u'Асеновград')
        assert u'터르고비슈테' == self.hangulize(u'Търговище')
        assert u'스몰랸' == self.hangulize(u'Смолян')
        assert u'페슈테라' == self.hangulize(u'Пещера')
        assert u'카잔러크' == self.hangulize(u'Казанлък')
        assert u'커르잘리' == self.hangulize(u'Кърджали')
        assert u'즐라토그라드' == self.hangulize(u'Златоград')
        assert u'큐스텐딜' == self.hangulize(u'Кюстендил')
        assert u'에프크시노그라드' == self.hangulize(u'Евксиноград')
        assert u'두란쿨라크' == self.hangulize(u'Дуранкулак')
        assert u'로도피' == self.hangulize(u'Родопи')
        assert u'이스커르' == self.hangulize(u'Искър')
        assert u'네세버르' == self.hangulize(u'Несебър')
