# -*- coding: utf-8 -*-
from tests import HangulizeTestCase
from hangulize.langs.bul import Bulgarian


class BulgarianTestCase(HangulizeTestCase):

    lang = Bulgarian()

    def test_people(self):
        assert u'디미터르 베르바토프' == self.hangulize(u'Димитър Бербатов')
        assert u'페터르 베론' == self.hangulize(u'Петър Берон')
        assert u'일리야 베슈코프' == self.hangulize(u'Илия Бешков')
        assert u'페터르 보그단' == self.hangulize(u'Петър Богдан')
        assert u'흐리스토 보테프' == self.hangulize(u'Христо Ботев')
        assert u'즐라툐 보야지에프' == self.hangulize(u'Златьо Бояджиев')
        assert u'니콜라 밥차로프' == self.hangulize(u'Никола Вапцаров')
        assert u'가브릴 라도미르' == self.hangulize(u'Гаврил Радомир')
        assert u'이반 에프스트라티에프 게쇼프' == \
              self.hangulize(u'Иван Евстратиев Гешов')
        assert u'마리야 그로즈데바' == self.hangulize(u'Мария Гроздева')
        assert u'니콜라이 갸우로프' == self.hangulize(u'Николай Гяуров')
        assert u'에카테리나 다포프스카' == self.hangulize(u'Екатерина Дафовска')
        assert u'그리고르 디미트로프' == self.hangulize(u'Григор Димитров')
        assert u'게나 디미트로바' == self.hangulize(u'Гeна Димитpова')
        assert u'갈리나 두르무슐리스카' == \
              self.hangulize(u'Галина Дурмушлийска')
        assert u'찬코 듀스타바노프' == self.hangulize(u'Цанко Дюстабанов')
        assert u'류드밀라 댜코프스카' == self.hangulize(u'Людмила Дяковска')
        assert u'토도르 지프코프' == self.hangulize(u'Тодор Живков')
        assert u'이반 릴스키' == self.hangulize(u'Иван Рилски')
        assert u'레네타 인조바' == self.hangulize(u'Ренета Инджова')
        assert u'엘레나 욘체바' == self.hangulize(u'Елена Йончева')
        assert u'아센 요르다노프' == self.hangulize(u'Асен Йорданов')
        assert u'라이나 카바이반스카' == self.hangulize(u'Райна Кабаиванска')
        assert u'마테이 카지스키' == self.hangulize(u'Матей Казийски')
        assert u'콘스탄틴 티흐' == self.hangulize(u'Константин Тих')
        assert u'알레코 콘스탄티노프' == self.hangulize(u'Алеко Константинов')
        assert u'에밀 코스타디노프' == self.hangulize(u'Емил Костадинов')
        assert u'스테프카 코스타디노바' == self.hangulize(u'Стефка Костадинова')
        assert u'크룸' == self.hangulize(u'Крум')
        assert u'율리야 크러스테바' == self.hangulize(u'Юлия Кръстева')
        assert u'베셀라 레체바' == self.hangulize(u'Весела Лечева')
        assert u'요르단 레치코프' == self.hangulize(u'Йордан Лечков')
        assert u'안드레이 루카노프' == self.hangulize(u'Андрей Луканов')
        assert u'디미터르 메한지스키' == self.hangulize(u'Димитър Механджийски')
        assert u'이반 밀레프' == self.hangulize(u'Иван Милев')
        assert u'미하일 시슈만' == self.hangulize(u'Михаил Шишман')
        assert u'이반 머르크비치카' == self.hangulize(u'Иван Мърквичка')
        assert u'게오르기 나자코프' == self.hangulize(u'Георги Наджаков')
        assert u'이반 파블로프' == self.hangulize(u'Иван Павлов')
        assert u'파이시 힐렌다르스키' == self.hangulize(u'Паисий Хилендарски')
        assert u'스틸리얀 페트로프' == self.hangulize(u'Стилиян Петров')
        assert u'그리고르 퍼를리체프' == self.hangulize(u'Григор Пърличев')
        assert u'안나마리야 라브노폴스카딘' == \
               self.hangulize(u'Анна-Мария Равнополска-Дийн')
        assert u'알렉산더르 라이체프' == self.hangulize(u'Александър Райчев')
        assert u'시메온 벨리키' == self.hangulize(u'Симеон Велики')
        assert u'펜초 슬라베이코프' == self.hangulize(u'Пенчо Славейков')
        assert u'스테판 스탐볼로프' == self.hangulize(u'Стефан Стамболов')
        assert u'테오도시 시나이츠키' == self.hangulize(u'Теодосий Синаитски')
        assert u'츠베탄 토도로프' == self.hangulize(u'Цветан Тодоров')
        assert u'흐리스토 스토이치코프' == self.hangulize(u'Христо Стоичков')
        assert u'보리스 흐리스토프' == self.hangulize(u'Борис Христов')
        assert u'그리고리 참블라크' == self.hangulize(u'Григорий Цамблак')
        assert u'드라간 찬코프' == self.hangulize(u'Драган Цанков')
        assert u'흐리스토 야바셰프' == self.hangulize(u'Христо Явашев')

    def test_places(self):
        assert u'아세노브그라드' == self.hangulize(u'Асеновград')
        assert u'반스코' == self.hangulize(u'Банско')
        assert u'부르가스' == self.hangulize(u'Бургас')
        assert u'바르나' == self.hangulize(u'Варна')
        assert u'데브냐' == self.hangulize(u'Девня')
        assert u'도브리치' == self.hangulize(u'Добрич')
        assert u'도버르스코' == self.hangulize(u'Добърско')
        assert u'두란쿨라크' == self.hangulize(u'Дуранкулак')
        assert u'에프크시노그라드' == self.hangulize(u'Евксиноград')
        assert u'즐라토그라드' == self.hangulize(u'Златоград')
        assert u'이스커르' == self.hangulize(u'Искър')
        assert u'이스페리흐' == self.hangulize(u'Исперих')
        assert u'카잔러크' == self.hangulize(u'Казанлък')
        assert u'커르잘리' == self.hangulize(u'Кърджали')
        assert u'큐스텐딜' == self.hangulize(u'Кюстендил')
        assert u'마다라' == self.hangulize(u'Мадара')
        assert u'말코 터르노보' == self.hangulize(u'Малко Търново')
        assert u'멜니크' == self.hangulize(u'Мелник')
        assert u'무살라' == self.hangulize(u'Мусала')
        assert u'네세버르' == self.hangulize(u'Несебър')
        assert u'파나규리슈테' == self.hangulize(u'Панагюрище')
        assert u'페트리치' == self.hangulize(u'Петрич')
        assert u'페슈테라' == self.hangulize(u'Пещера')
        assert u'피린' == self.hangulize(u'Пирин')
        assert u'플레벤' == self.hangulize(u'Плевен')
        assert u'플로브디프' == self.hangulize(u'Пловдив')
        assert u'랄리차' == self.hangulize(u'Ралица')
        assert u'릴라' == self.hangulize(u'Рила')
        assert u'로도피' == self.hangulize(u'Родопи')
        assert u'스베슈타리' == self.hangulize(u'Свещари')
        assert u'소조폴' == self.hangulize(u'Созопол')
        assert u'소피야' == self.hangulize(u'София')
        assert u'슬리벤' == self.hangulize(u'Сливен')
        assert u'스몰랸' == self.hangulize(u'Смолян')
        assert u'스타라 자고라' == self.hangulize(u'Стара Загора')
        assert u'터르고비슈테' == self.hangulize(u'Търговище')