# -*- coding: utf-8 -*-
from tests import HangulizeTestCase
from hangulize.langs.ca import Catalan


class CatalanTestCase(HangulizeTestCase):

    lang = Catalan()

    def test_people(self):
        assert u'아란차' == self.hangulize(u'Arantxa')
        assert u'발렌티 알미랄' == self.hangulize(u'Valentí Almirall')
        assert u'자우메 바르투메우' == self.hangulize(u'Jaume Bartumeu')
        assert u'세르지 브루게라' == self.hangulize(u'Sergi Bruguera')
        assert u'산티아고 칼라트라바' == self.hangulize(u'Santiago Calatrava')
        assert u'조안 캅데빌라' == self.hangulize(u'Joan Capdevila')
        assert u'조제프 카르네르' == self.hangulize(u'Josep Carner')
        assert u'파우 카잘스' == self.hangulize(u'Pau Casals')
        assert u'류이스 콤파니스' == self.hangulize(u'Lluís Companys')
        assert u'알렉스 코레자' == self.hangulize(u'Àlex Corretja')
        assert u'알베르트 코스타' == self.hangulize(u'Albert Costa')
        assert u'살바도르 달리' == self.hangulize(u'Salvador Dalí')
        assert u'살바도르 에스프리우' == self.hangulize(u'Salvador Espriu')
        assert u'세스크 파브레가스' == self.hangulize(u'Cesc Fàbregas')
        assert u'파우 가졸' == self.hangulize(u'Pau Gasol')
        assert u'안토니 가우디' == self.hangulize(u'Antoni Gaudí')
        assert u'조제프 과르디올라' == self.hangulize(u'Josep Guardiola')
        assert u'샤비 에르난데스' == self.hangulize(u'Xavi Hernández')
        assert u'라몬 률' == self.hangulize(u'Ramon Llull')
        assert u'프란세스크 마시아 이 류사' == \
               self.hangulize(u'Francesc Macià i Llussà')
        assert u'조안 마라갈' == self.hangulize(u'Joan Maragall')
        assert u'조아노트 마르토렐' == self.hangulize(u'Joanot Martorell')
        assert u'조안 미로' == self.hangulize(u'Joan Miró')
        assert u'제라르트 피케' == self.hangulize(u'Gerard Piqué')
        assert u'조제프 플라' == self.hangulize(u'Josep Pla')
        assert u'에우달 프라델' == self.hangulize(u'Eudald Pradell')
        assert u'카를레스 푸욜' == self.hangulize(u'Carles Puyol')
        assert u'메르세 로도레다' == self.hangulize(u'Mercè Rodoreda')
        assert u'조르디 사발' == self.hangulize(u'Jordi Savall')
        assert u'조아킴 소롤랴' == self.hangulize(u'Joaquim Sorolla')
        assert u'안토니 타피에스' == self.hangulize(u'Antoni Tàpies')
        assert u'조르디 타레스' == self.hangulize(u'Jordi Tarrés')
        assert u'자신 베르다게르' == self.hangulize(u'Jacint Verdaguer')
        
    def test_places(self):
        assert u'알라칸' == self.hangulize(u'Alacant')
        assert u'안도라' == self.hangulize(u'Andorra')
        assert u'안도라 라 벨랴' == self.hangulize(u'Andorra la Vella')
        assert u'바르셀로나' == self.hangulize(u'Barcelona')
        assert u'베르가' == self.hangulize(u'Berga')
        assert u'베잘루' == self.hangulize(u'Besalú')
        assert u'카탈루냐' == self.hangulize(u'Catalunya')
        assert u'세르다냐' == self.hangulize(u'Cerdanya')
        assert u'콘플렌' == self.hangulize(u'Conflent')
        assert u'에이비사' == self.hangulize(u'Eivissa')
        assert u'엘시' == self.hangulize(u'Elx')
        assert u'엠푸리에스' == self.hangulize(u'Empúries')
        assert u'지로나' == self.hangulize(u'Girona')
        assert u'만레자' == self.hangulize(u'Manresa')
        assert u'몬주이크' == self.hangulize(u'Montjuïc')
        assert u'오조나' == self.hangulize(u'Osona')
        assert u'팔랴르스' == self.hangulize(u'Pallars')
        assert u'팔랴르스 주사' == self.hangulize(u'Pallars Jussà')
        assert u'팔랴르스 소비라' == self.hangulize(u'Pallars Sobirà')
        assert u'팔마' == self.hangulize(u'Palma')
        assert u'리바고르사' == self.hangulize(u'Ribagorça')
        assert u'로셀료' == self.hangulize(u'Rosselló')
        assert u'우르젤' == self.hangulize(u'Urgell')
        assert u'발렌시아' == self.hangulize(u'València')

    def test_miscellaneous(self):
        assert u'바르사' == self.hangulize(u'Barça')
        assert u'캄 노우' == self.hangulize(u'Camp Nou')
        assert u'카니고' == self.hangulize(u'Canigó')
        assert u'에스파뇰' == self.hangulize(u'Espanyol')
        assert u'에스텔라르' == self.hangulize(u'estel·lar')
        assert u'레나셴사' == self.hangulize(u'Renaixença')
