# -*- coding: utf-8 -*-
from ..language import Language
from ..notation import Notation
from ..phoneme import *


class Italian(Language):
    """The language for italian."""

    vowels = 'a', 'e', 'i', 'o', 'u'
    notation = Notation(
        ('^gli$',    phonemes(u'리')),
        ('^glia$',   phonemes(u'글리아')),
        ('^glioma$', phonemes(u'글리오마')),
        ('^gli{@}',  'li'),
        ('{@}gli',   'li'),
        ('gn{@}',    'nJ'),
        ('gn',       'n'),
        ('gg',       'g'),
        ('gi{aou}',  'G'),
        ('g{ei}',    'G'),
        ('ss',       's'),
        ('sce',      'sJe'),
        ('sci',      'si'),
        ('cc',       'c'),
        ('ci{aou}',  'z'),
        ('c{ei}',    'z'),
        ('c',        'k'),
        ('qq',       'q'),
        ('quo',      'kuo'),
        ('qu{aei}',  'kW'),
        ('quy',      'kWi'),
        ('q',        'k'),
        ('xx',       'x'),
        ('x',        'ks'),
        ('tt',       't'),
        ('ts',       'z'),
        ('w',        'v'),
        ('aa',       'a'),
        ('bb',       'b'),
        ('dd',       'd'),
        ('ee',       'e'),
        ('ff',       'f'),
        ('hh',       'h'),
        ('{@}h{@}',  (Choseong(NG),)),
        ('h',        None),
        ('ii',       'i'),
        ('jj',       'j'),
        ('j{@}',     'J'),
        ('j',        'i'),
        ('kk',       'k'),
        ('ll',       'l'),
        ('{@}mm{@}', (Jongseong(M), Choseong(M))),
        ('mm',       'm'),
        ('{@}nn{@}', (Jongseong(N), Choseong(N))),
        ('oo',       'o'),
        ('pp',       'p'),
        ('rr',       'r'),
        ('tt',       't'),
        ('uu',       'u'),
        ('vv',       'v'),
        ('^y{@}',    'J'),
        ('yy',       'y'),
        ('y',        'i'),
        ('zz',       'z'),
        ('b',        (Choseong(B),)),
        ('d',        (Choseong(D),)),
        ('f',        (Choseong(P),)),
        ('g',        (Choseong(G),)),
        ('G',        (Choseong(J),)),
        ('k',        (Choseong(K),)),
        ('^l',       (Choseong(L),)),
        ('l{@}',     (Jongseong(L), Choseong(L))),
        ('l',        (Jongseong(L),)),
        ('m{@}',     (Choseong(M),)),
        ('m',        (Jongseong(M),)),
        ('n{@J}',     (Choseong(N),)),
        ('n',        (Jongseong(N),)),
        ('p',        (Choseong(P),)),
        ('r',        (Choseong(L),)),
        ('s',        (Choseong(S),)),
        ('t',        (Choseong(T),)),
        ('v',        (Choseong(B),)),
        ('z',        (Choseong(C),)),
        ('Ja',       (Jungseong(YA),)),
        ('Je',       (Jungseong(YE),)),
        ('Ji',       (Jungseong(I),)),
        ('Jo',       (Jungseong(YO),)),
        ('Ju',       (Jungseong(YU),)),
        ('Wa',       (Jungseong(WA),)),
        ('We',       (Jungseong(WE),)),
        ('Wi',       (Jungseong(WI),)),
        ('a',        (Jungseong(A),)),
        ('e',        (Jungseong(E),)),
        ('i',        (Jungseong(I),)),
        ('o',        (Jungseong(O),)),
        ('u',        (Jungseong(U),)),
    )


it = Italian
