# -*- coding: utf-8 -*-
import re
from hangulize import *


class Italian(Language):
    """For transcribing Italian."""

    vowels = 'aeiou'
    notation = Notation(
        ('^gli$',         split_phonemes(u'리')),
        ('^glia$',        split_phonemes(u'글리아')),
        ('^glioma$',      split_phonemes(u'글리오마')),
        ('^gli{@}',       'li'),
        ('{@}gli',        'li'),
        ('gn{@}',         'nJ'),
        ('gn',            'n'),
        ('gg',            'g'),
        ('gi{a|o|u}',     'G'),
        ('g{e|i}',        'G'),
        ('ss',            's'),
        ('sce',           'sJe'),
        ('sci',           'si'),
        ('cc',            'c'),
        ('ci{a|o|u}',     'z'),
        ('c{e|i}',        'z'),
        ('c',             'k'),
        ('qq',            'q'),
        ('quo',           'kuo'),
        ('qu{a|e|i}',     'kW'),
        ('quy',           'kWi'),
        ('q',             'k'),
        ('xx',            'x'),
        ('x',             'ks'),
        ('tt',            't'),
        ('ts',            'z'),
        ('w',             'v'),
        ('aa',            'a'),
        ('bb',            'b'),
        ('dd',            'd'),
        ('ee',            'e'),
        ('ff',            'f'),
        ('hh',            'h'),
        ('{@}h{@}',       Choseong(NG)),
        ('h',             None),
        ('ii',            'i'),
        ('jj',            'j'),
        ('^j{@}',         'J'),
        ('{@}j{@}',       'J'),
        ('j',             'i'),
        ('kk',            'k'),
        ('ll',            'l'),
        ('{@}mm{@}',      Jongseong(M), Choseong(M)),
        ('mm',            'm'),
        ('{@}nn{@}',      Jongseong(N), Choseong(N)),
        ('oo',            'o'),
        ('pp',            'p'),
        ('rr',            'r'),
        ('tt',            't'),
        ('uu',            'u'),
        ('vv',            'v'),
        ('^y{@}',         'J'),
        ('yy',            'y'),
        ('y',             'i'),
        ('zz',            'z'),
        ('b',             Choseong(B)),
        ('d',             Choseong(D)),
        ('f',             Choseong(P)),
        ('g',             Choseong(G)),
        ('G',             Choseong(J)),
        ('{@}k{p|s|t|z}', Jongseong(G)),
        ('k',             Choseong(K)),
        ('^m',            'P'),
        ('^n',            'Q'),
        ('^l',            Choseong(L)),
        ('{m|n}l',        Choseong(L)),
        ('l{@}',          Jongseong(L), Choseong(L)),
        ('l',             Jongseong(L)),
        ('P',             Choseong(M)),
        ('m{@}',          Choseong(M)),
        ('m',             Jongseong(M)),
        ('Q',             Choseong(N)),
        ('n{@|J}',        Choseong(N)),
        ('n',             Jongseong(N)),
        ('p',             Choseong(P)),
        ('r',             Choseong(L)),
        ('s',             Choseong(S)),
        ('t',             Choseong(T)),
        ('v',             Choseong(B)),
        ('z',             Choseong(C)),
        ('Ja',            Jungseong(YA)),
        ('Je',            Jungseong(YE)),
        ('Ji',            Jungseong(I)),
        ('Jo',            Jungseong(YO)),
        ('Ju',            Jungseong(YU)),
        ('Wa',            Jungseong(WA)),
        ('We',            Jungseong(WE)),
        ('Wi',            Jungseong(WI)),
        ('a',             Jungseong(A)),
        ('e',             Jungseong(E)),
        ('i',             Jungseong(I)),
        ('o',             Jungseong(O)),
        ('u',             Jungseong(U)),
    )

    def normalize(self, string):
        chars_pattern = self.chars_pattern
        pattern = "(?<=[%s])'(?=[%s])" % (chars_pattern, chars_pattern)
        return re.sub(pattern, '', normalize_roman(string))


it = Italian
