# -*- coding: utf-8 -*-
from hangulize import *


class Polish(Language):
    """For transcribing Polish."""

    vowels = 'aeiouy'
    consonants = 'cfhkpst'
    notation = Notation([
        (u'ą{l|ł}',          'o'),
        (u'ą',               'oN'),
        (u'ę{l|ł}',          'e'),
        (u'ę$',              'e'),
        (u'ę',               'eN'),
        (u'ół',              'u'),
        (u'łł',              u'ł'),
        (u'ł{@}',            'W'),
        (u'ł',               'Xu'),
        (u'ó',               'u'),
        ('rz',               u'ż'),
        (u'dź',              u'ć'),
        (u'ć',               'cj'),
        ('hh',               'h'),
        ('ch',               'h'),
        (u'ź{<consonants>}', 'sj'),
        (u'ź$',              'sj'),
        (u'ź',               'zj'),
        (u'ś',               'sj'),
        ('dz{<consonants>}', 'c'),
        ('dz$',              'c'),
        ('dz',               'z'),
        (u'dż{@}',           'z'),
        (u'dż',              'C'),
        ('cz',               'C'),
        ('cj',               'C'),
        (u'C$',              'ci'),
        ('C{@}',             'c'),
        ('C',                'ci'),
        ('b{<consonants>}',  'p'),
        ('b$',               'p'),
        ('d{<consonants>}',  't'),
        ('d$',               't'),
        ('g{<consonants>}',  'k'),
        ('g$',               'k'),
        ('w{<consonants>}',  'f'),
        ('w$',               'f'),
        (u'ż{<consonants>}', 'sz'),
        (u'{<consonants>}ż', 'sz'),
        (u'ż$',              'sz'),
        (u'ż{@}',            'z'),
        (u'żj',              'zj'),
        (u'ż',               'zu'),
        ('sz{@}',            'sJ'),
        ('szj',              'sJ'),
        ('sz$',              'si'),
        ('sz',               'sJu'),
        ('z{<consonants>}',  's'),
        ('z$',               's'),
        ('xx',               'x'),
        ('x',                'ks'),
        ('tt',               't'),
        ('w',                'v'),
        ('q',                'kv'),
        ('aa',               'a'),
        ('bb',               'b'),
        ('dd',               'd'),
        ('ee',               'e'),
        ('ff',               'f'),
        ('jj',               'ij'),
        ('ii',               'i'),
        ('zj{@}',            'z'),
        ('j{@}',             'J'),
        ('j',                'i'),
        ('ij',               'i'),
        ('yj',               'y'),
        ('kk',               'k'),
        ('ll',               'l'),
        ('{@}mm{@}',         Jongseong(M), Choseong(M)),
        ('mm',               'm'),
        ('{@}nn{@}',         Jongseong(N), Choseong(N)),
        ('oo',               'o'),
        ('pp',               'p'),
        ('rr',               'r'),
        ('ss',               's'),
        ('tt',               't'),
        ('uu',               'u'),
        ('X',                None),
        ('vv',               'v'),
        ('^y{@}',            'J'),
        ('yy',               'y'),
        ('y',                'i'),
        ('zz',               'z'),
        ('^k',               Choseong(K)),
        ('{@}k{p|s|t|z}',    Jongseong(G)),
        ('^p',               Choseong(P)),
        ('{@}p{k|s|t|z}',    Jongseong(B)),
        ('k',                Choseong(K)),
        ('p',                Choseong(P)),
        ('b',                Choseong(B)),
        ('c',                Choseong(C)),
        ('d',                Choseong(D)),
        ('f',                Choseong(P)),
        ('g',                Choseong(G)),
        ('h',                Choseong(H)),
        ('^m',               'P'),
        ('^n',               'Q'),
        ('^l',               Choseong(L)),
        ('{m|n}l',           Choseong(L)),
        ('l{@|J}',           Jongseong(L), Choseong(L)),
        ('l',                Jongseong(L)),
        ('P',                Choseong(M)),
        ('m{@|J}',           Choseong(M)),
        ('m',                Jongseong(M)),
        ('Q',                Choseong(N)),
        ('n{@|J}',           Choseong(N)),
        ('n',                Jongseong(N)),
        ('N',                Jongseong(NG)),
        ('r',                Choseong(L)),
        ('s',                Choseong(S)),
        ('t',                Choseong(T)),
        ('v',                Choseong(B)),
        ('z',                Choseong(J)),
        ('Ja',               Jungseong(YA)),
        ('Je',               Jungseong(YE)),
        ('Ji',               Jungseong(I)),
        ('Jo',               Jungseong(YO)),
        ('Ju',               Jungseong(YU)),
        ('Wa',               Choseong(NG), Jungseong(WA)),
        ('We',               Choseong(NG), Jungseong(WE)),
        ('Wi',               Choseong(NG), Jungseong(WI)),
        ('Wo',               Choseong(NG), Jungseong(WEO)),
        ('Wu',               Choseong(NG), Jungseong(U)),
        ('a',                Jungseong(A)),
        ('e',                Jungseong(E)),
        ('i',                Jungseong(I)),
        ('o',                Jungseong(O)),
        ('u',                Jungseong(U))
    ])

    def normalize(self, string):
        def normalize_only_unsafe(string):
            map = {u'Ą': u'ą',
                   u'Ć': u'ć',
                   u'Ę': u'ę',
                   u'Ł': u'ł',
                   u'Ó': u'ó',
                   u'Ś': u'ś',
                   u'Ź': u'ź',
                   u'Ż': u'ż'}
            safe = map.keys() + map.values()
            for c in string:
                if c not in safe:
                    yield normalize_roman(c)
                elif c in map:
                    yield map[c]
                else:
                    yield c
        return ''.join(normalize_only_unsafe(string))


pl = Polish
