# -*- coding: utf-8 -*-
from hangulize import *


class Swedish(Language):
    """For transcribing Swedish."""

    vowels = 'a', 'A', 'e', 'E', 'i', 'o', 'O', 'u', 'y'
    """Convention: A = å, E = ä, O = ö"""
    notation = Notation(
        (u'å',            'A'),
        (u'ä',            'E'),
        (u'ö',            'O'),
        ('w',             'v'),
        ('adjO',          'ajO'),
        ('berg',          'beri'),
        ('borg',          'bori'),
        ('dvErg',         'dvEri'),
        ('fErg',          'fEri'),
        ('karg',          'kari'),
        ('korg',          'kori'),
        ('mErg',          'mEri'),
        ('sorg',          'sori'),
        ('torg',          'tori'),
        ('varg',          'vari'),
        ('norge',         'norje'),
        ('sverige',       'sverije'),
        ('gata$',         'Gata'),
        ('gatan$',        'Gatan'),
        ('giva',          'jiva'),
        ('gift',          'jift'),
        ('genom',         'jenom'),
        ('geir',          'Geir'),
        ('gren$',         'Gren'),
        ('grens$',        'Grens'),
        ('guyan',         'Gaian'),
        ('kebnekaise',    'Kebnekaise'),
        ('kelvin',        'Kelvin'),
        ('kelviA',        'KelviA'),
        ('kennet',        'Kennet'),
        ('^keke',         'Keke'),
        ('^kent',         'Kent'),
        ('kexholm',       'Kexholm'),
        ('^kim',          'Kim'),
        ('kiruna',        'Kiruna'),
        ('^kO$',          'KO'),
        ('^bilkO',        'bilKO'),
        ('^kOer$',        'KOer'),
        ('^kOren$',       'KOren'),
        ('^kOrfestival',  'KOrfestival'),
        ('^kymmen',       'Kymmen'),
        ('lysekil',       'lyseSil'),
        ('guyan',         'Gaian'),
        ('mEnnisk',       'mEnniS'),
        ('sjuk',          'sjukX'), # arbitrary rule
        ('xx',            'x'),
        ('x',             'ks'),
        ('ds',            's'),
        ('sch{@}',        'S'),
        ('sch',           'Su'),
        ('^sk{eEiOy}',    'S'),
        ('sk{EOy}',       'S'),
        ('^sk{eEiOy}',    'S'),
        ('sk{EOy}',       'S'),
        ('skj',           'S'),
        ('stj',           'S'),
        ('kj',            'S'),
        ('sj',            'S'),
        ('tj',            'S'),
        ('^g{eEiOy}',     'j'),
        ('g{EOy}',        'j'),
        ('^k{eEiOy}',     'S'),
        ('k{EOy}',        'S'),
        ('ch{@}',         'S'),
        ('ch',            'k'),
        ('c{eiy}',        's'),
        ('c',             'k'),
        ('tionde',        'tiXonde'),
        ('tion',          'Son'),
        ('^dj',           'j'),
        ('gj',            'j'),
        ('hj',            'j'),
        ('^lj',           'j'),
        ('lg$',           'li'),
        ('lg{@lr}',       'lG'),
        ('lg',            'li'),
        ('rg$',           'ri'),
        ('rg{l@r}',       'rG'),
        ('rg',            'ri'),
        ('rl',            'l'),
        ('qu',            'kv'),
        ('q',             'k'),
        ('{@}gn',         'Nn'),
        ('ng',            'N'),
        ('nkt',           'Nt'),
        ('nk',            'Nk'),
        ('mn$',           'm'),
        ('th',            't'),
        ('z',             's'),
        ('jO',            'je'),
        ('SO',            'Se'),
        ('S{@}',          'sJ'),
        ('S',             'si'),
        ('^j{@}',         'J'),
        ('{@}j{@}',       'J'),
        ('j',             'i'),
        ('G',             'g'),
        ('K',             'k'),
        ('aa',            'a'),
        ('bb',            'b'),
        ('dd',            'd'),
        ('ee',            'e'),
        ('ff',            'f'),
        ('gg',            'g'),
        ('hh',            'h'),
        ('ii',            'i'),
        ('jj',            'j'),
        ('kk',            'k'),
        ('ll',            'l'),
        ('{@}mm{@}',      (Jongseong(M), Choseong(M))),
        ('mm',            'm'),
        ('{@}nn{@}',      (Jongseong(N), Choseong(N))),
        ('nn',            'n'),
        ('oo',            'o'),
        ('pp',            'p'),
        ('rr',            'r'),
        ('ss',            's'),
        ('tt',            't'),
        ('uu',            'u'),
        ('vv',            'v'),
        ('yy',            'y'),
        ('zz',            'z'),
        ('A',             'o'),
        ('E',             'e'),
        ('h{@}',          'H'),
        ('h',             None),
        ('H',             'h'),
        ('^b',            (Choseong(B),)),
        ('{@}b{fhkpst}',  (Jongseong(B),)),
        ('b',             (Choseong(B),)),
        ('^g',            (Choseong(G),)),
        ('{@}g{fhkpst}',  (Jongseong(G),)),
        ('g',             (Choseong(G),)),
        ('^k',            (Choseong(K),)),
        ('{@}k{fhpst}',   (Jongseong(G),)),
        ('^p',            (Choseong(P),)),
        ('{@}p{fhkst}',   (Jongseong(B),)),
        ('^t',            (Choseong(T),)),
        ('{@}t{fhkps}',   (Jongseong(S),)),
        ('k',             (Choseong(K),)),
        ('p',             (Choseong(P),)),
        ('t',             (Choseong(T),)),
        ('d',             (Choseong(D),)),
        ('f',             (Choseong(P),)),
        ('g',             (Choseong(G),)),
        ('h{@}',          (Choseong(H),)),
        ('^m',            'P'),
        ('^n',            'Q'),
        ('^l',            (Choseong(L),)),
        ('{mn}l',         (Choseong(L),)),
        ('l{@}',          (Jongseong(L), Choseong(L))),
        ('lm{@}',         (Jongseong(L), Choseong(M))),
        ('ln{@}',         (Jongseong(L), Choseong(N))),
        ('lm',            (Jongseong(L), Choseong(L), Jongseong(M))),
        ('ln',            (Jongseong(L), Choseong(L), Jongseong(N))),
        ('l',             (Jongseong(L),)),
        ('P',             (Choseong(M),)),
        ('m{@}',          (Choseong(M),)),
        ('m',             (Jongseong(M),)),
        ('Q',             (Choseong(N),)),
        ('n{@}',          (Choseong(N),)),
        ('n',             (Jongseong(N),)),
        ('N',             (Jongseong(NG),)),
        ('r',             (Choseong(L),)),
        ('s',             (Choseong(S),)),
        ('v',             (Choseong(B),)),
        ('Ja',            (Jungseong(YA),)),
        ('Je',            (Jungseong(YE),)),
        ('Ji',            (Jungseong(I),)),
        ('Jo',            (Jungseong(YO),)),
        ('Ju',            (Jungseong(YU),)),
        ('Jy',            (Jungseong(WI),)),
        ('a',             (Jungseong(A),)),
        ('e',             (Jungseong(E),)),
        ('i',             (Jungseong(I),)),
        ('o',             (Jungseong(O),)),
        ('u',             (Jungseong(U),)),
        ('y',             (Jungseong(WI),)),
        ('O',             (Jungseong(OE),)),
    )

    def normalize(self, string):
        def normalize_only_unsafe(string):
            map = {u'Å': u'å',
                   u'Ǻ': u'å',
                   u'ǻ': u'å',
                   u'Ä': u'ä',
                   u'Ö': u'ö',
                   u'Æ': u'ä',
                   u'æ': u'ä',
                   u'Ø': u'ö',
                   u'ø': u'ö',
                   u'Ç': 's',
                   u'ç': 's',
                   u'Ü': 'y',
                   u'ü': 'y'}
            safe = map.keys() + map.values()
            for c in string:
                if c not in safe:
                    yield normalize_roman(c)
                elif c in map:
                    yield map[c]
                else:
                    yield c
        return ''.join(normalize_only_unsafe(string))


sv = Swedish

